# Generated by Django 4.1.6 on 2023-02-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
