# Generated by Django 4.1.6 on 2023-02-26 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_categoryname_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
