# Generated by Django 4.1.6 on 2023-02-26 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_description_alter_listing_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='time_placed',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='time_placed',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='time_posted',
            new_name='time',
        ),
    ]
