# Generated by Django 4.1.6 on 2023-03-16 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_time_placed_bid_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
